resource_group_name = "my-resource-group"
location            = "East US"
vnet_name           = "my-vnet"
subnet_name         = "my-subnet"
vm_name             = "my-windows-vm"
vm_size             = "Standard_DS1_v2"
admin_username      = "adminuser"
admin_password      = "P@ssw0rd1234!"